config/routes.rb
Rails.application.routes.draw do
  resources :foods
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  before_save :do_this
  has_one_attached :picture
  enum category: [ :starter, :tacos, :drinks, :deserts, :others ]


  def do_this
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy!

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :es_name, :ca_name, :fa_name, :category, :content, :es_content, :fa_content, :ca_content, :price, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @foods = Food.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<%= image_tag food.picture.variant(resize_to_limit: [600, 600]) %>

<h3>
  <%= food.name %>
</h3>

<h4>
  <%= food.category %>
</p>

<p>
  <%= food.content %>
</p>

<p>
  <strong>
    <%= food.price %>
  </strong>
      <%= link_to "Show this food", food %>
</p>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :es_name, style: "display: block" %>
    <%= form.text_field :es_name %>
  </div>
  <div>
    <%= form.label :ca_name, style: "display: block" %>
    <%= form.text_field :ca_name %>
  </div>
  <div>
    <%= form.label :fa_name, style: "display: block" %>
    <%= form.text_field :fa_name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, options_for_select(Food.categories.map {|key, value| [key.titleize, Food.categories.key(value)]}, @food.category) %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.label :es_content, style: "display: block" %>
    <%= form.text_area :es_content %>
  </div>
  <div>
    <%= form.label :ca_content, style: "display: block" %>
    <%= form.text_area :ca_content %>
  </div>
  <div>
    <%= form.label :fa_content, style: "display: block" %>
    <%= form.text_area :fa_content %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.file_field :picture %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foods</h1>

<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <p>
      <%= link_to "Show this food", food %>
    </p>
  <% end %>
</div>

<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monchidos</title>
    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<header>
  <nav>
    <a href="/"><img alt="Logo" src="/logo.svg" height="70"></a>
  </nav>
  <h1>Vegan real food</h1>

</header>

<main>
  <hr>
    <section id="section-1">
      <% @foods.each do |food| %>
        <aside>
          <%= render food %>
        </aside>
      <% end %>
    </section>
  </hr>
</main>